"""Write viewer/live-data.js from a possession working directory.

    python -m tools.make_view work/p0001

The viewer opens from `file://` with no server, and a page loaded that way cannot
`fetch` a sibling JSON file — so the possession is handed over as a script that
assigns `window.POSSESSION`, the same arrangement `viewer/data.js` uses for the
fixture. The video is referenced by relative path rather than copied: it is a
30 MB clip of somebody else's broadcast, `docs/10-getting-the-footage.md` says not
to redistribute it, and `work/` is gitignored for that reason.

Four files go across, because the viewer's four panes need them and a second
request is not available from `file://`:

- `possession.json` — the positions, as `window.POSSESSION`;
- `issues.json` — the "needs a human" queue, as `window.ISSUES`;
- `identities.json` — voted jersey numbers, as `window.IDENTITIES`, and merged
  onto each slot so the overlay can label it;
- `events.json` — hand-tagged and suggested events, onto `POSSESSION.events`.

Only the first is required. A working directory that has not reached M5 still
renders; the panes that have nothing say so.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


def _maybe(work: Path, name: str) -> dict | None:
    p = work / name
    if not p.exists():
        print(f"[make_view] - {name} not present; that pane will say so")
        return None
    return json.loads(p.read_text(encoding="utf-8"))


def build(work: Path, out: Path, video: str | None = None) -> Path:
    doc = json.loads((work / "possession.json").read_text(encoding="utf-8"))
    clip = work / "clip.mp4"
    if video is None:
        video = os.path.relpath(clip, out.parent).replace("\\", "/")
    doc["video_src"] = video
    if not clip.exists():
        print(f"[make_view] ! {clip} is missing; the page will show no video")

    ident = _maybe(work, "identities.json")
    if ident:
        # A jersey the vote declined to call stays None. docs/04 M5: a wrong
        # number is worse than no number, and the viewer must not paper over it.
        by = {s["slot"]: s for s in ident["slots"]}
        named = 0
        for p in doc["players"]:
            s = by.get(p["slot"])
            if s and s.get("jersey") is not None:
                p["jersey"] = s["jersey"]
                p["jersey_confidence"] = s.get("confidence")
                named += 1
        print(f"[make_view] + identities.json: {named} of {len(doc['players'])} "
              "slots carry a voted jersey")

    ev = _maybe(work, "events.json")
    if ev:
        doc["events"] = ev.get("events", [])
        print(f"[make_view] + events.json: {len(doc['events'])} event(s)")

    issues = _maybe(work, "issues.json")
    if issues:
        print(f"[make_view] + issues.json: {len(issues.get('issues', []))} open")

    out.parent.mkdir(parents=True, exist_ok=True)
    lines = ["// Generated by tools/make_view.py. Do not edit.",
             "// Real measured output. Read the provenance banner in the viewer "
             "before quoting any number.",
             f"window.POSSESSION = {json.dumps(doc, separators=(',', ':'))};"]
    if issues:
        lines.append(f"window.ISSUES = {json.dumps(issues, separators=(',', ':'))};")
    if ident:
        lines.append(f"window.IDENTITIES = {json.dumps(ident, separators=(',', ':'))};")
    out.write_text(chr(10).join(lines) + chr(10), encoding="utf-8")
    return out


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="tools.make_view")
    p.add_argument("work")
    p.add_argument("--out", default="viewer/live-data.js")
    p.add_argument("--video", default=None,
                   help="override the relative path to the clip")
    a = p.parse_args(argv)
    out = build(Path(a.work), Path(a.out), a.video)
    print(f"[make_view] wrote {out} ({out.stat().st_size / 1e6:.2f} MB)")
    print("[make_view] open viewer/index.html directly in a browser")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
