"""Write viewer/live-data.js from a possession working directory.

    python -m tools.make_view work/p0001

The viewer opens from `file://` with no server, and a page loaded that way cannot
`fetch` a sibling JSON file — so the possession is handed over as a script that
assigns `window.POSSESSION`, the same arrangement `viewer/prototype.html` uses for
the fixture. The video is referenced by relative path rather than copied: it is a
30 MB clip of somebody else's broadcast, `docs/10-getting-the-footage.md` says not
to redistribute it, and `work/` is gitignored for that reason.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


def build(work: Path, out: Path, video: str | None = None) -> Path:
    doc = json.loads((work / "possession.json").read_text(encoding="utf-8"))
    clip = work / "clip.mp4"
    if video is None:
        video = os.path.relpath(clip, out.parent).replace("\\", "/")
    doc["video_src"] = video
    if not clip.exists():
        print(f"[make_view] ! {clip} is missing; the page will show no video")

    out.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(doc, separators=(",", ":"))
    out.write_text(
        "// Generated by tools/make_view.py. Do not edit.\n"
        "// Positions are real and measured; slot identities are a stand-in (see notice).\n"
        f"window.POSSESSION = {body};\n", encoding="utf-8")
    return out


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="tools.make_view")
    p.add_argument("work")
    p.add_argument("--out", default="viewer/live-data.js")
    p.add_argument("--video", default=None,
                   help="override the relative path to the clip")
    a = p.parse_args(argv)
    out = build(Path(a.work), Path(a.out), a.video)
    print(f"[make_view] wrote {out} ({out.stat().st_size / 1e6:.2f} MB)")
    print(f"[make_view] open viewer/live.html directly in a browser")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
